export enum USER_ROLE {
  CUSTOMER = "CUSTOMER",
  FACILITY_STAFF = "FACILITY_STAFF",
  FACILITY_MANAGER = "FACILITY_MANAGER",
  BUSINESS_OPS_MANAGER = "BUSINESS_OPS_MANAGER",
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
}
